version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: currency_rate_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=currency_rate_service
      - EMAIL=currency.rate@zohomail.eu
      - EMAIL_PASS=xd8mPck1YURj
      - EMAIL_HOST=smtp.zoho.eu
      - EMAIL_PORT=465
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  db_data: {}
